nelmio_api_doc:
    documentation:
        info:
            title: Notification Publisher
            description: Microservice for sending notifications to users
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc