networks:
  default: 
  web-server-network:

services:
  php:
    build:
      context: ./docker/php
      target: app_base
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/var/www
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-rabbit}:${RABBITMQ_PASS:-pass}@rabbitmq:5672
    healthcheck:
      test: "cgi-fcgi -bind -connect localhost:9000 >/dev/null 2>&1 || exit 1"
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - default
      - web-server-network

  nginx:
    image: nginx:1.29.1-alpine
    depends_on:
      php:
        condition: service_healthy
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/var/www/public
    networks:
      - web-server-network

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.0.7-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbit}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-pass}
    volumes:
      - ./docker/rabbitmq:/etc/rabbitmq
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
  
  php-queue-consumer:
    build:
      context: ./docker/php
      target: app_consumer
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/php/consumer:/etc/supervisor/
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-rabbit}:${RABBITMQ_PASS:-pass}@rabbitmq:5672
    entrypoint: ""
    command: "supervisord"
    depends_on: 
      rabbitmq:
        condition: service_healthy
      php:
        condition: service_healthy
    networks:
      - default
