controllers:
    resource:
        path: ../src/Notification/Management/UI/Http/Controller/
        namespace: App\Notification\Management\UI\Http\Controller
    type: attribute
    prefix: '/api'
    trailing_slash_on_root: false