notification_management:
    resource:
        path: ../src/Notification/Management/UI/Http/Controller/
        namespace: App\Notification\Management\UI\Http\Controller
    type: attribute
    prefix: '/api'
    trailing_slash_on_root: false

Notification_delivery:
    resource:
        path: ../src/Notification/Delivery/UI/Http/Controller/
        namespace: App\Notification\Delivery\UI\Http\Controller
    type: attribute
    prefix: '/api'
    trailing_slash_on_root: false

home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /api/doc
        permanent: true