# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'
    enable_email_channel: '%env(bool:ENABLE_EMAIL_CHANNEL)%'
    enable_sms_channel: '%env(bool:ENABLE_SMS_CHANNEL)%'
    alert_rate_limit: '%env(int:ALERT_RATE_LIMIT)%'
    env(ALERT_RATE_LIMIT): 300
    env(AVAILABLE_COMMUNICATION_CHANNELS): '["email", "sms"]'
    env(INFO_COMMUNICATION_CHANNELS): '["email"]'
    env(DELIVERY_MAX_RETRIES): 3
    env(DELIVERY_RETRY_DELAY): 2000
    env(DELIVERY_RETRY_DELAY_MULTIPLIER): 2
    notification_management.rate_policy.config:
        alert:
            max_per_hour: '%env(int:ALERT_RATE_LIMIT)%'
    notification_delivery.notification_type_channels_policy.config:
        info:
            channels: '%env(json:INFO_COMMUNICATION_CHANNELS)%'
    notification_delivery.available_channels_policy.config:
        channels: '%env(json:AVAILABLE_COMMUNICATION_CHANNELS)%'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'
    _instanceof:
        App\Application\Service\NotificationChannelServiceInterface:
            tags: ['notification_channel_service']

        App\Notification\Management\Domain\Service\NotificationManagementPolicyInterface:
            tags: ['notification_management_policy_service']
        
        App\Notification\Delivery\Domain\Service\NotificationDeliveryPolicyInterface:
            tags: ['notification_delivery_policy_service']

        App\Notification\Delivery\Infrastructure\Service\CommunicationChannelSenderInterface:
            tags: ['communication_channel_sender']

    App\Domain\Policy\AvailableChannelsPolicy:
        arguments:
            $enableEmail: '%enable_email_channel%'
            $enableSms: '%enable_sms_channel%'

    App\Domain\Policy\RatePolicy:
        arguments:
            $alertRateLimit: '%alert_rate_limit%'

    App\Notification\Management\Domain\Service\RatePolicy:
        arguments:
            $config: !service
                factory: ['@App\Shared\Infrastructure\Config\ConfigFactory', 'create']
                arguments:
                    - '%notification_management.rate_policy.config%'
                    - 'App\Notification\Management\Domain\Config\RateConfig[]'

    App\Notification\Management\Domain\Factory\NotificationFactory:
        arguments:
            $notificationManagementPolicies: !tagged_iterator notification_management_policy_service

    App\Notification\Delivery\Domain\Service\NotificationTypeChannelsPolicy:
        arguments:
            $config: !service
                factory: ['@App\Shared\Infrastructure\Config\ConfigFactory', 'create']
                arguments:
                    - '%notification_delivery.notification_type_channels_policy.config%'
                    - 'App\Notification\Delivery\Domain\Config\AvailableChannelsConfig[]'

    App\Notification\Delivery\Domain\Service\AvailableChannelsPolicy:
        arguments:
            $config: !service
                factory: ['@App\Shared\Infrastructure\Config\ConfigFactory', 'create']
                arguments:
                    - '%notification_delivery.available_channels_policy.config%'
                    - 'App\Notification\Delivery\Domain\Config\AvailableChannelsConfig'

    App\Notification\Delivery\Domain\Service\DeliveryRetryPolicy:
        arguments:
            $maxRetries: '%env(int:DELIVERY_MAX_RETRIES)%'
            $retryDelay: '%env(int:DELIVERY_RETRY_DELAY)%'
            $retryDelayMultiplier: '%env(int:DELIVERY_RETRY_DELAY_MULTIPLIER)%'